package Extensions::TestExtension::TrafficOpsRoutes;

use strict;
use warnings;

sub new {
        my $self = {};
        my $class = shift;
        return ( bless( $self, $class ) );
}

sub define {
        my $self = shift;
        my $r    = shift;
        
	#open(my $fh, '>', '/tmp/report_.txt');
	#print $fh "My first report generated by perl\n";
	#close $fh;

	$r->add_condition(not_ldap => sub {
                my ($route, $c, $captures, $hash) = @_;
                return 0 if &UI::Utils::is_ldap($c);
                return 1;
        });

        my $namespace = "Extensions::TestExtension";
        $self->test_routes($r, $namespace);
}

sub test_routes {
        my $self = shift;
        my $r = shift;
        my $namespace = shift;

	$r->get('/test_path')->over( authenticated => 1, not_ldap => 1 )->to( 'Foo#hello', namespace => $namespace );
}

1;
